// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type SensorReading struct {
	Timestamp time.Time
	ChillerID string
	SensorID  string
	Sensor    string
	Value     float64
}
