// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_readings.sql

package db

import (
	"context"
	"time"
)

const insertSensorReading = `-- name: InsertSensorReading :exec
INSERT INTO sensor_readings (timestamp, sensor, sensor_id, value)
VALUES ($1, $2, $3, $4)
`

type InsertSensorReadingParams struct {
	Timestamp time.Time
	Sensor    string
	SensorID  string
	Value     float64
}

func (q *Queries) InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertSensorReading,
		arg.Timestamp,
		arg.Sensor,
		arg.SensorID,
		arg.Value,
	)
	return err
}
