FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o myapp ./cmd/api

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

RUN adduser -D appuser
USER appuser

WORKDIR  /home/appuser

COPY --from=builder /app/myapp .

ENV PORT=8080

ENV GIN_MODE=release

EXPOSE 8080

CMD ["./myapp"]
